esd:
  profiles:
    active: local
  server:
    name: esd-server
    worker_num: 4
    max_conn: 1024
    debug: true
    enable_static_handler: 1
    document_root: ${WWW_DIR}
  port:
    http:
      host: 0.0.0.0
      port: 80
      open_http_protocol: true
      sock_type: 1